canteens:
  thm: 289
  uma: 285
timeout: 5
filename:
  thm_week: "thm_week_menu.txt"
  thm: "thm_menu.txt"
  uma_week: "unima_week_menu.txt"
  abo: "abos.txt"
messages:
  start: "Willkommen beim inoffiziellen Mensabot"
  help: "/mensa - heutiges Mensa Menü an der Hochschule\nthm_week - Mensa Menü an der Hochschule für diese Woche\nuni_week - Mensa Menü an der Uni für diese Woche"
  abo: "du wirst jetzt täglich Infos zur mensa erhalten"
  deabo: "du wirst jetzt täglich **keine** Infos zur mensa erhalten"